apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    layer: webserver
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
